/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Android Runtime Fuzzer tool (3.5.002). Mon Jul 27 17:53:02 2015
// srand = 18549618822946597416045128773174602736294746070280799450840672702967

package OptimizationTests.regression.test2370_1;

public class Main {

    public static final int N = 100;

public static int iMeth(long l1, int i2) {

    int d = 20;
    float f=2.565F;
    long lArr[]=new long[N];
    int i3=39185, i4=39954, i6=0, i7=-58207;

    i3 = 1;
    f += l1;
    for (int i5 = 1; i5 < 12; i5++) {
        f *= (i6);
        i7 -= (--i7);
        d *= (f / ((2 * lArr[i3]) | 1));
        i6 = i2;
        i7 = i4 * i4;
        i6 -= d;
    }
    return i7;
}

public static void main(String[] strArr) {
    System.out.println("res: " + iMeth(123L, 10));
}
}
