/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Android Runtime Fuzzer tool (3.5.002). Sat Jul 11 23:31:11 2015
// srand = 16612790621703052677013446717101782825011970795781919899358422385514

package OptimizationTests.regression.test2335;

import OptimizationTests.regression.shared.*;

public class Main extends FuzzerUtils {

public static void main(String[] strArr) {

    float f1=-2.178F;
    int i4=-20545;
    double dArr[]=new double[100];

    int i2 = 1, i3 = 2;

    for (i4 = 4; i4 < 82; i4++) {
        i2 *= (int)(dArr[i4 - 1] + i3);
        i2 += (int)(dArr[i4 - 1] = 46);
        f1 = (float)dArr[i4 - 1];

    }

    System.out.println("f1: " + f1);
}
}
