/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Dalvik Fuzzer tool (3.4.001). Wed Nov 26 19:20:25 2014
package OptimizationTests.regression.test934_3;

import OptimizationTests.regression.shared.*;

public class Main {
    public static final int N = 100;

    public static void main(String[] i74) {
        int oq = -47769, n85 = -4494, ocy = 25666;
        long j = -6891736890734774656L, yh[] = new long[N];
        n85 = 1;
        while (++n85 < 85) {
            for (ocy = n85; ocy > n85; ocy--) {
                oq -= -1331;
                oq *= (j++) + yh[ocy];
            }
        }
        System.out.println("n85 ocy = " + n85 + "," + ocy);
    }
}
