/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Android Runtime Fuzzer tool (3.5.002). Mon Jul 27 17:53:02 2015
// srand = 18549618822946597416045128773174602736294746070280799450840672702967

package OptimizationTests.regression.test2370_2;

public class Main {

public static void main(String[] strArr) {
    long l = 123;
    int i=15, i5=5, i6=62;

    i = 1;
    while ((i += 2) < 96) {
        i6 -= -3;
        i5 += (int)l;
    }

    System.out.println("i6 = " + i6);
}
}
