/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package OptimizationTests.regression.test105871;

/*
 * The test is based on test1.java generated by Dalvik Fuzzer on Mon May  6 00:27:01 2013 
 */
public class Main {

	public static final int N = 100;

	private static void init(int[] a, int n, int seed) {
		for (int j = 0; j < n; j++) {
			a[j] = ((j % 2 == 0) ? seed + j : seed - j) % 65535;
		}
	}

	public static void main(String[] args) {
		int sn = 36369, jv = -13244, k = 52995, j = -16824, kl8 = 2204, d = 10422, n0 = -19587, aa = -52770, k3 = -8436, jw = -30070, nh = 12765, res = 12362;

		int re0[] = new int[N], s[][] = new int[N][N], tc[] = new int[N], iw2[] = new int[N], md3[] = new int[N], x[] = new int[N], n[] = new int[N], l[] = new int[N], u9[] = new int[N], q[] = new int[N], vw4[] = new int[N];

		init(re0, N, 35381);
		init(tc, N, 13236);
		init(iw2, N, 56042);
		init(md3, N, 35035);
		init(x, N, 21354);
		init(n, N, 10670);
		init(l, N, 62379);
		init(u9, N, 2403);
		init(q, N, 35695);
		init(vw4, N, 19382);

		for (kl8 = 4; kl8 < 84; kl8 += 3) {
			md3[kl8 - 1] += x[kl8];
			d = x[kl8];
			sn += sn * (((n0++) - kl8) - d);
		}

		n0 += n[19];
		aa -= l[36];
		
		for (k3 = 3; k3 < 97; k3++) {
			iw2[k3 - 1] = x[k3];
			jw = sn - (tc[k3]);
			if (aa > 0)
				break;

			u9[k3] += md3[k3 + 1];
			x[k3 - 1] += q[k3 + 1];
		}

                System.out.println("jw = " + jw);
	}
}
