/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Dalvik Fuzzer tool (3.1.005). Mon Jan 20 16:41:25 2014
package OptimizationTests.regression.test165878;

import OptimizationTests.regression.shared.*;

public class Main extends FuzzerUtils {

    public static final int N = 6000;

    public static void main(String[] w5n) {

        int a = -53427, www = 11855, hc = -7520, id = -4542, nw5 = 26416, t2v = -6894, n = 49451, th = 28194, e6 = 4495, j = -47326, m = -20004, vu = 39008, b = -56011, ga[] = new int[N];
        boolean ex = false;
        double bd = 24.284, s = 47.347, nm = 98.767;
        float zc = -88.683F;
        long hoi = -5589080538554403438L, fsr = -7498613668633408712L, ufh[] = new long[N];
        byte p = 97;

        init(ufh, 1468302970900414491L);
        init(ga, 5532);

        for (a = 1; a < 5999; ++a) {
            try {
                www = (a / a);
                id = (hc / 91);
                id = (-179 / nw5);
            } catch (ArithmeticException a_e) {
            }
            try {
                nw5 <<= (id - (hc--));
                id = (int) ((long) ((-(t2v + a)) * (26174 / (zc + zc))) >> (hoi >>= (49250 * (-21217 % n))));
            } catch (ArithmeticException v6) {
                nw5 += (~a);
                t2v = (int) ((--ufh[a + 1]) * (hc >>> (-(id -= th))));
                for (e6 = 31; e6 > 1; --e6) {
                    for (j = e6; j < e6; ++j) {
                        m = (int) ((long) ((bd - id) * (nw5 << p)) >> ((t2v + vu) + (nw5 * 27139)));
                        if ((ex = ((-(th - -3001087889599413748L)) < (hoi - hc))) || false)
                            continue;
                        hoi = (long) (((++www) * (bd - b)) - ((hoi--) + (6420705745418667785L + (-46692 << (-(-(b / 54325)))))));
                        vu %= (int) ((long) ((n - (s + -44366)) * hc) | 1);
                    }
                    th = (vu & (ga[e6 + 1]--));
                }
            } finally {
                nm = (m = (int) (www * (fsr * 24959)));
            }
        }

        System.out.println("a www hc = " + a + "," + www + "," + hc);
        System.out.println("id nw5 t2v = " + id + "," + nw5 + "," + t2v);
        System.out.println("zc hoi n = " + Float.floatToIntBits(zc) + "," + hoi
                + "," + n);
        System.out.println("th e6 j = " + th + "," + e6 + "," + j);
        System.out.println("m bd p = " + m + "," + Double.doubleToLongBits(bd)
                + "," + p);
        System.out.println("vu ex b = " + vu + "," + ex + "," + b);
        System.out.println("s nm fsr = " + Double.doubleToLongBits(s) + ","
                + Double.doubleToLongBits(nm) + "," + fsr);
        System.out.println("ufh ga = " + checkSum(ufh) + "," + checkSum(ga));

    }
}
