/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Android Runtime Fuzzer tool (3.5.002). Mon Jul 13 12:49:36 2015
// srand = 15238104916030760501860602478146838002005411463366387409232067721652

package OptimizationTests.regression.test2287;

import OptimizationTests.regression.shared.*;

public class Main extends FuzzerUtils {

    public static final int N = 100;

    public static void main(String[] strArr) {

        double d=0.121649;
        int i=-62, iArr1[]=new int[N];
        long l1=-4340626106676763472L;

        init(iArr1, 46);

        for (i = 4; i < 6; ++i) {
            iArr1[(int)(d + 1)] *= (int)(iArr1[(int)(d + 1)] = (int)(l1));
        }

        System.out.println("iArr1 = " + checkSum(iArr1));
    }
}