/*
 * Copyright (C) 2015 Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Dalvik Fuzzer tool (3.5.001). Thu Feb  5 12:32:48 2015
package OptimizationTests.regression.test1116_2;

public class Main {

    public static void main(String[] strArr) {

        long l = 202L;
        short s = -4704;
        float f1 = -86.63F;
        int i = -12, i2 = -58431, i3 = 14, i4 = -7018, i5 = -9, i6 = -87, i7 = -187;

        while (++i2 < 34) {
            for (i3 = 58; i3 > 2; i3 -= 2) {
                i = (int) f1;
                l = i2 + Math.min(46369099L, l);
                i4 += (int) i6;
                i6 *= (++s);
            }
            for (i7 = 1; i7 < 90; ++i7) {
                i = --i5;
                l = (long) (l);
            }
        }

        System.out.println("i l i1 = " + i + "," + l + ",");
    }
}
