#!/bin/bash
#
# Copyright (C) 2015 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


packagedir=`echo "$(cd $(dirname $0); pwd)/../"`

declare -a testMethodsCounts=('test1:Complex Loop is already bottom tested (after gotos)!Rewrite loop' 'test2:Complex Loop is already bottom tested (after gotos)!Rewrite loop' 'test3:Complex Loop is already bottom tested (after gotos)!Rewrite loop'  'test4:Too many or too few exit blocks!is already bottom tested' 'test5:Complex Loop is already bottom tested (after gotos)' 'test6:Complex Loop is already bottom tested (after gotos)!Rewrite loop' 'test7:Complex Loop is already bottom tested (after gotos)!Rewrite loop' 'test8:Result is used by!Rewrite loop' 'test9:Complex Loop is already bottom tested (after gotos)!Rewrite loop' 'test10:Complex Loop is already bottom tested (after gotos)' 'test11:Complex Loop is already bottom tested (after gotos)'  'test12:Complex Loop is already bottom tested (after gotos)'  )

# include the package's postproc
if [ -f $packagedir/postproc_common ]; then
    source $packagedir/postproc_common
fi

